---
name: 'Issue Labeler'
on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write
  contents: read

jobs:
  label_issues:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml
          enable-versioned-regex: 0
          include-title: 1
